version: '3.1'
# Postgres service
services:
  postgresdb:
    image: postgres:latest
    environment:
      POSTGRES_USER: project_admin_user
      POSTGRES_PASSWORD: Passw0rd
      POSTGRES_DB: ecommerce
    networks:
      - airflow
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./data:/data
      - ./infra_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql

  webserver: 
    environment:
      AIRFLOW__CORE__TEST_CONNECTION: 'Enabled'
